live_config_reload = true
# import = ["~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"]
# This is the github page where the themes come from
# https://github.com/alacritty/alacritty-theme

[window]
blur = true
opacity = 0.6
decorations = "None"
padding = { x = 5, y = 5 }

[font]
size = 14
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
offset = { x = 2 }

[terminal]
osc52 = "CopyPaste"

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off" }
