live_config_reload = true

[window]
blur = true
opacity = 0.4
decorations = "None"
padding = { x = 5, y = 5 }

[font]
size = 13
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
offset = {x = 2}

[terminal]
osc52 = "CopyPaste"
