require "config.keymaps"
require "config.options"
require "config.plugins"
require "config.colorscheme"
require "config.lsp.init"
require "config.nvim-tree"
-- require "config.treesitter"
require "config.whichkey"
require "config.hop"
require "config.customFunctions"
